version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo Installing Serverless framework
      - npm install -g serverless@3.0.0
  pre_build:
    commands:
      - echo Installing project dependencies
      - cd ${REPO}
      - npm install
  build:
    commands:
      - echo Deploying with Serverless framework
      - sls deploy -s dev
